# Generated by Django 5.2.8 on 2025-11-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='menu_item',
            new_name='menu_item_id',
        ),
    ]
